attributes:
  ORGANIZATIONNAME: Blockchain Luxembourg S.A
include:
  Modules/BlockchainComponentLibrary/project.yml
configs:
  Debug Dev: debug
  Debug Production: debug
  Debug Staging: debug
  Debug Alpha: debug
  Release Alpha: release
  Release: release
  Release Internal: release
  Release Staging: release
fileGroups:
  - README.md
name: Blockchain
options:
  bundleIdPrefix: com.rainydayapps
  defaultConfig: Release
  deploymentTarget:
    iOS: '14.0'
  groupSortPosition: bottom
  platform: iOS
  postGenCommand: ./scripts/add_test_targets
schemeTemplates:
  BlockchainScheme:
    analyze:
      config: ${debugConfig}
    archive:
      config: ${releaseConfig}
      customArchiveName: Blockchain
    build:
      targets:
        Blockchain: build
    profile:
      config: ${releaseConfig}
    run:
      config: ${debugConfig}
      environmentVariables:
        - variable: BLOCKCHAIN_DEBUG_NETWORK_REQUEST
          value: "TRUE"
          isEnabled: false
        - variable: OS_ACTIVITY_MODE
          value: disable
          isEnabled: true
      commandLineArguments:
        "-_UIConstraintBasedLayoutLogUnsatisfiable NO": true
    test:
      config: ${debugConfig}
      gatherCoverageData: true
      targets:
        - name: BlockchainTests
          randomExecutionOrder: true
schemes:
  Blockchain:
    templateAttributes:
      debugConfig: Debug Production
      releaseConfig: Release
    templates:
      - BlockchainScheme
  Blockchain (Dev):
    templateAttributes:
      debugConfig: Debug Dev
      releaseConfig: Release
    templates:
      - BlockchainScheme
  Blockchain (Internal Production):
    templateAttributes:
      debugConfig: Debug Production
      releaseConfig: Release Internal
    templates:
      - BlockchainScheme
  Blockchain (Staging):
    templateAttributes:
      debugConfig: Debug Staging
      releaseConfig: Release Staging
    templates:
      - BlockchainScheme
  Blockchain (Alpha):
    templateAttributes:
      debugConfig: Debug Alpha
      releaseConfig: Release Alpha
    templates:
      - BlockchainScheme
settingGroups:
  base_ios:
    base:
      TARGETED_DEVICE_FAMILY: 1
  base_signing:
    base:
      CODE_SIGN_ENTITLEMENTS: Blockchain/Blockchain.entitlements
      CODE_SIGN_STYLE: Manual
      DEVELOPMENT_TEAM: NZ6PH75U7K

  debug_signing_dev:
    base:
      CODE_SIGN_IDENTITY: iPhone Developer
      PROVISIONING_PROFILE_SPECIFIER: match Development com.rainydayapps.Blockchain.dev
    groups:
      - base_signing
  debug_signing_staging:
    base:
      CODE_SIGN_IDENTITY: iPhone Developer
      PROVISIONING_PROFILE_SPECIFIER: match Development com.rainydayapps.Blockchain.staging
    groups:
      - base_signing
  release_signing_staging:
    base:
      CODE_SIGN_IDENTITY: iPhone Distribution
      PROVISIONING_PROFILE_SPECIFIER: match AdHoc com.rainydayapps.Blockchain.staging
    groups:
      - base_signing
  debug_signing_alpha:
    base:
      CODE_SIGN_IDENTITY: iPhone Developer
      PROVISIONING_PROFILE_SPECIFIER: match Development com.rainydayapps.Blockchain.alpha
    groups:
      - base_signing
  release_signing_alpha:
    base:
      CODE_SIGN_IDENTITY: iPhone Distribution
      PROVISIONING_PROFILE_SPECIFIER: match AppStore com.rainydayapps.Blockchain.alpha
    groups:
    - base_signing
  debug_signing:
    base:
      CODE_SIGN_IDENTITY: iPhone Developer
      PROVISIONING_PROFILE_SPECIFIER: match Development com.rainydayapps.Blockchain
    groups:
    - base_signing
  release_signing_internal:
    base:
      CODE_SIGN_IDENTITY: iPhone Distribution
      PROVISIONING_PROFILE_SPECIFIER: match AdHoc com.rainydayapps.Blockchain
    groups:
    - base_signing
  release_signing:
    base:
      CODE_SIGN_IDENTITY: iPhone Distribution
      PROVISIONING_PROFILE_SPECIFIER: match AppStore com.rainydayapps.Blockchain
    groups:
    - base_signing

settings:
  base:
    CODE_SIGN_STYLE: Manual
    ENABLE_BITCODE: false
    SUPPORTS_MACCATALYST: false
    VALID_ARCHS: arm64
    VALID_ARCHS[sdk=iphonesimulator*]: x86_64
  configs:
    Debug Dev:
      OTHER_SWIFT_FLAGS: -DINTERNAL_BUILD
    Debug Production:
      OTHER_SWIFT_FLAGS: -DINTERNAL_BUILD
    Debug Staging:
      OTHER_SWIFT_FLAGS: -DINTERNAL_BUILD
    Debug Alpha:
      OTHER_SWIFT_FLAGS: -DINTERNAL_BUILD -DALPHA_BUILD
    Release Internal:
      OTHER_SWIFT_FLAGS: -DINTERNAL_BUILD
    Release Staging:
      OTHER_SWIFT_FLAGS: -DINTERNAL_BUILD
    Release Alpha:
      OTHER_SWIFT_FLAGS: -DINTERNAL_BUILD -DALPHA_BUILD
packages:
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    version: 1.9.0
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    version: 0.34.0
  Intercom:
    url: https://github.com/intercom/intercom-ios.git
    version: 12.1.0
  DIKit:
    url: https://github.com/jackpooleybc/DIKit.git
    branch: safe-property-wrappers
  BigInt:
    url: https://github.com/attaswift/BigInt.git
    version: 5.3.0
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift.git
    version: 6.5.0
  RIBs:
    url: https://github.com/uber/RIBs.git
    version: 0.12.2
  Pulse:
    url: https://github.com/kean/Pulse.git
    version: 0.20.2
  Analytics:
    path: Modules/Analytics
  BlockchainNamespace:
    path: Modules/BlockchainNamespace
  RxAnalytics:
    path: Modules/RxAnalytics
  CommonCrypto:
    path: Modules/CommonCrypto
  ComposableArchitectureExtensions:
    path: Modules/ComposableArchitectureExtensions
  CryptoAssets:
    path: Modules/CryptoAssets
  FeatureApp:
    path: Modules/FeatureApp
  FeatureAccountPicker:
    path: Modules/FeatureAccountPicker
  FeatureActivity:
    path: Modules/FeatureActivity
  FeatureAuthentication:
    path: Modules/FeatureAuthentication
  FeatureCardPayment:
    path: Modules/FeatureCardPayment
  FeatureCardIssuing:
    path: Modules/FeatureCardIssuing
  FeatureDashboard:
    path: Modules/FeatureDashboard
  FeatureCryptoDomain:
    path: Modules/FeatureCryptoDomain
  FeatureCoin:
    path: Modules/FeatureCoin
  FeatureDebug:
    path: Modules/FeatureDebug
  FeatureForm:
    path: Modules/FeatureForm
  FeatureInterest:
    path: Modules/FeatureInterest
  FeatureKYC:
    path: Modules/FeatureKYC
  FeatureNFT:
    path: Modules/FeatureNFT
  FeatureOpenBanking:
    path: Modules/FeatureOpenBanking
  FeatureOnboarding:
    path: Modules/FeatureOnboarding
  FeatureProducts:
    path: Modules/FeatureProducts
  FeatureQRCodeScanner:
    path: Modules/FeatureQRCodeScanner
  FeatureSettings:
    path: Modules/FeatureSettings
  FeatureNotificationPreferences:
    path: Modules/FeatureNotificationPreferences
  FeatureTour:
    path: Modules/FeatureTour
  FeatureTransaction:
    path: Modules/FeatureTransaction
  FeatureWithdrawalLocks:
    path: Modules/FeatureWithdrawalLocks
  FeatureWalletConnect:
    path: Modules/FeatureWalletConnect
  HDWallet:
    path: Modules/HDWallet
  Keychain:
    path: Modules/Keychain
  Localization:
    path: Modules/Localization
  Metadata:
    path: Modules/Metadata
  Network:
    path: Modules/Network
  NetworkErrors:
    path: Modules/NetworkErrors
  Money:
    path: Modules/Money
  Platform:
    path: Modules/Platform
  RemoteNotifications:
    path: Modules/RemoteNotifications
  Test:
    path: Modules/Test
  Tool:
    path: Modules/Tool
  RxTool:
    path: Modules/RxTool
  UIComponents:
    path: Modules/UIComponents
  WalletPayload:
    path: Modules/WalletPayload
  BlockchainComponentLibrary:
    path: Modules/BlockchainComponentLibrary
targets:
  Blockchain:
    configFiles:
      Debug Dev: Config/BlockchainConfig/Blockchain-Dev.xcconfig
      Debug Production: Config/BlockchainConfig/Blockchain-Production.xcconfig
      Debug Staging: Config/BlockchainConfig/Blockchain-Staging.xcconfig
      Debug Alpha: Config/BlockchainConfig/Blockchain-Alpha.xcconfig
      Release: Config/BlockchainConfig/Blockchain-Production.xcconfig
      Release Internal: Config/BlockchainConfig/Blockchain-Production.xcconfig
      Release Staging: Config/BlockchainConfig/Blockchain-Staging.xcconfig
      Release Alpha: Config/BlockchainConfig/Blockchain-Alpha.xcconfig
    dependencies:
      - sdk: libicucore.tbd
      - framework: Carthage/Build/FirebaseABTesting.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseAnalytics.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseCore.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseCoreDiagnostics.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseCrashlytics.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseDynamicLinks.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseInstallations.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseMessaging.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseRemoteConfig.xcframework
        embed: false
      - framework: Carthage/Build/GoogleAppMeasurement.xcframework
        embed: false
      - framework: Carthage/Build/GoogleDataTransport.xcframework
        embed: false
      - framework: Carthage/Build/GoogleUtilities.xcframework
        embed: false
      - framework: Carthage/Build/nanopb.xcframework
        embed: false
      - framework: Carthage/Build/PromisesObjC.xcframework
        embed: false
      - framework: Carthage/Build/recaptcha.framework
        embed: false
      - framework: Carthage/Build/GoogleToolboxForMac.xcframework
        embed: false
      - framework: Carthage/Build/GTMSessionFetcher.xcframework
        embed: false
      - framework: Carthage/Build/Protobuf.xcframework
        embed: false
      - framework: Carthage/Build/Promises.xcframework
        embed: false
      - framework: Carthage/Build/Sift.xcframework
      - embed: false
        framework: Submodules/OpenSSL-for-iPhone/lib/libcrypto.a

      - package: FeatureAccountPicker
      - package: FeatureActivity
      - package: FeatureApp
      - package: FeatureAuthentication
      - package: FeatureCardPayment
      - package: FeatureCardIssuing
      - package: FeatureDashboard
      - package: FeatureCryptoDomain
      - package: FeatureCoin
      - package: FeatureDebug
      - package: FeatureForm
      - package: FeatureInterest
      - package: FeatureNotificationPreferences
      - package: FeatureKYC
      - package: FeatureNFT
      - package: FeatureQRCodeScanner
      - package: FeatureOnboarding
      - package: FeatureOpenBanking
      - package: FeatureProducts
        product: FeatureProductsData
      - package: FeatureProducts
        product: FeatureProductsDomain
      - package: FeatureSettings
      - package: FeatureTour
      - package: FeatureTransaction
      - package: FeatureWithdrawalLocks
      - package: FeatureWalletConnect

      - package: BigInt
      - package: ComposableArchitecture
      - package: DIKit
      - package: RIBs
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
      - package: RxSwift
        product: RxSwift
      - package: Pulse
        product: PulseUI
      - package: Pulse
        product: PulseCore
      - package: Intercom

      - package: Analytics
        product: AnalyticsKit
      - package: BlockchainNamespace
      - package: RxAnalytics
        product: RxAnalyticsKit
      - package: CommonCrypto
        product: CommonCryptoKit
      - package: CryptoAssets
        product: BitcoinCashKit
      - package: CryptoAssets
        product: BitcoinChainKit
      - package: CryptoAssets
        product: BitcoinKit
      - package: CryptoAssets
        product: EthereumKit
      - package: CryptoAssets
        product: ERC20Kit
      - package: CryptoAssets
        product: ERC20DataKit
      - package: CryptoAssets
        product: StellarKit
      - package: HDWallet
        product: HDWalletKit
      - package: Keychain
        product: KeychainKit
      - package: Localization
        product: Localization
      - package: Metadata
        product: MetadataKit
      - package: Metadata
        product: MetadataDataKit
      - package: Network
        product: NetworkKit
      - package: NetworkErrors
        product: NetworkErrors
      - package: Money
        product: MoneyKit
      - package: Platform
        product: PlatformKit
      - package: Platform
        product: PlatformDataKit
      - package: Platform
        product: PlatformUIKit
      - package: RemoteNotifications
        product: RemoteNotificationsKit
      - package: Tool
        product: ToolKit
      - package: RxTool
        product: RxToolKit
      - package: UIComponents
        product: UIComponents
      - package: WalletPayload
        product: WalletPayloadKit
      - package: WalletPayload
        product: WalletPayloadDataKit

    platform: iOS
    postBuildScripts:
      - name: Run Crashlytics
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - ${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}
        script: ${PROJECT_DIR}/scripts/crashlytics/run
    postCompileScripts:
      - name: Get SSL Certificate
        path: Blockchain/Scripts/get_ssl_certificate.sh
      - name: Swiftlint
        path: Blockchain/Scripts/swiftlint.sh
      - name: Setup Firebase Environment
        path: Blockchain/Scripts/firebase_copy_plist.sh
      - name: Envman BUILT_PRODUCTS_DIR
        path: Blockchain/Scripts/export_built_products_dir.sh
    preBuildScripts:
      - name: my-wallet SHA256
        script: "if [[ -z \"${BITRISE_PROJECT_PATH}\" ]]; then\n  exit 0\nfi\ncd ${PROJECT_DIR}\n\
          if ! shasum -a 256 -c ${PROJECT_DIR}/my-wallet.js.sha256; then\n  echo \"\
          Checksum failed:\" >&2\n  exit 1\nfi\n"
    settings:
      base:
        COMMIT_HASH: ${COMMIT_HASH}
        GCC_PREFIX_HEADER: Blockchain/Blockchain-Prefix.pch
        FRAMEWORK_SEARCH_PATHS:
          - $(PROJECT_DIR)/Carthage/Build/iOS/
          - $(PROJECT_DIR)/Carthage/Build/
          - Submodules/OpenSSL-for-iPhone/lib
        HEADER_SEARCH_PATHS:
          - $(PROJECT_DIR)/Submodules/OpenSSL-for-iPhone/include
        LIBRARY_SEARCH_PATHS:
          - $(PROJECT_DIR)/Submodules/OpenSSL-for-iPhone/lib
        OTHER_LDFLAGS:
          - -ObjC
        SWIFT_OBJC_BRIDGING_HEADER: Blockchain/Blockchain-Bridging-Header.h
      configs:
        Debug Dev:
          groups:
            - debug_signing_dev
            - base_ios
        Debug Staging:
          groups:
            - debug_signing_staging
            - base_ios
        Release Staging:
          groups:
            - release_signing_staging
            - base_ios
        Debug Alpha:
          groups:
            - debug_signing_alpha
            - base_ios
        Release Alpha:
          groups:
            - release_signing_alpha
            - base_ios
        Debug Production:
          groups:
            - debug_signing
            - base_ios
        Release:
          groups:
            - release_signing
            - base_ios
        Release Internal:
          groups:
            - release_signing_internal
            - base_ios
    sources:
      - buildPhase:
          copyFiles:
            destination: resources
        group: Blockchain/Cert
        optional: true
        path: Blockchain/Cert/blockchain.der
      - group: Blockchain/JavaScript
        optional: true
        path: Submodules/My-Wallet-V3/dist/my-wallet.js
      - excludes:
        - Firebase
        - Scripts
        - Cert
        path: Blockchain
      - includes:
        - BTCAddress.[hm]
        - BTCBase58.[hm]
        - BTCBigNumber.[hm]
        - BTCCurvePoint.[hm]
        - BTCData.[hm]
        - BTCErrors.[hm]
        - BTCKey.[hm]
        - BTCKeychain.[hm]
        - BTCNetwork.[hm]
        - BTCProtocolSerialization.[hm]
        - NSData+BTCData.[hm]
        path: Submodules/CoreBitcoin/CoreBitcoin
    type: application
  BlockchainTests:
    settings:
       OTHER_LDFLAGS: -undefined dynamic_lookup
    dependencies:
      - target: Blockchain
      - package: Test
        product: TestKit
      - package: RxSwift
        product: RxTest
      - package: RxSwift
        product: RxBlocking
    platform: iOS
    sources:
    - path: BlockchainTests
    - createIntermediateGroups: true
      path: Modules/Test/Sources/TestKit
    - createIntermediateGroups: true
      path: Modules/Tool/Sources/ToolKitMock
    - createIntermediateGroups: true
      path: Modules/NetworkErrors/Sources/NabuNetworkErrorMock
    - createIntermediateGroups: true
      path: Modules/Network/Sources/NetworkKitMock
    - createIntermediateGroups: true
      path: Modules/Money/Sources/MoneyKitMock
    - createIntermediateGroups: true
      path: Modules/Platform/Sources/PlatformKitMock
    - createIntermediateGroups: true
      path: Modules/Platform/Sources/PlatformUIKitMock
    - createIntermediateGroups: true
      path: Modules/RemoteNotifications/Sources/RemoteNotificationsKitMock
    - createIntermediateGroups: true
      path: Modules/FeatureAuthentication/Sources/FeatureAuthenticationMock
    - createIntermediateGroups: true
      path: Modules/FeatureKYC/Sources/FeatureKYCDomainMock
    - createIntermediateGroups: true
      path: Modules/FeatureKYC/Sources/FeatureKYCUIMock
    - createIntermediateGroups: true
      path: Modules/Analytics/Sources/AnalyticsKitMock
    - createIntermediateGroups: true
      path: Modules/FeatureSettings/Sources/FeatureSettingsDomainMock
    - createIntermediateGroups: true
      path: Modules/WalletPayload/Sources/WalletPayloadKitMock
    type: bundle.unit-test
  CryptoDomainDemo:
    dependencies:
      - package: FeatureCryptoDomain
        product: FeatureCryptoDomain
      - package: FeatureCryptoDomain
        product: FeatureCryptoDomainMock
    platform: iOS
    sources:
      - createIntermediateGroups: true
        path: Modules/FeatureCryptoDomain/CryptoDomainDemo
    type: application
  SnapshotTestsHostApp: # A target only used to host (unit) snapshot tests as they require a hosting app
    platform: iOS
    sources:
    - path: SnapshotTestsHostApp
    postBuildScripts:
      - path: scripts/fix-snapshot-host-app.sh
        name: "[blockchain] Copy Swift Package Manager Generated Bundles"
    type: application
