//
//  LocalizationConstants.h
//  Blockchain
//
//  Created by Tim Lee on 8/6/14.
//  Copyright (c) 2014 Blockchain Luxembourg S.A. All rights reserved.
//

#import <Foundation/Foundation.h>

#define BC_STRING_ADDRESS NSLocalizedString(@"Address", nil)
#define BC_STRING_ADDRESS_BOOK NSLocalizedString(@"Address book", nil)
#define BC_STRING_ADDRESSES NSLocalizedString(@"Addresses", nil)
#define BC_STRING_ADVANCED_USERS_ONLY NSLocalizedString(@"Advanced users only", nil)
#define BC_STRING_AMOUNT NSLocalizedString(@"Amount", nil)
#define BC_STRING_ANY_ADDRESS NSLocalizedString(@"Any address", nil)
#define BC_STRING_ARCHIVE NSLocalizedString(@"Archive", nil)
#define BC_STRING_ARCHIVE_FOOTER_TITLE NSLocalizedString(@"Archive this if you do NOT want to use it anymore. Your funds will remain safe, and you can unarchive it at any time.", nil)
#define BC_STRING_ARCHIVED NSLocalizedString(@"Archived", nil)
#define BC_STRING_ARCHIVED_FOOTER_TITLE NSLocalizedString(@"This is archived. Though you cannot send funds from here, any and all funds will remain safe. Simply unarchive to start using it again.", nil)
#define BC_STRING_ARCHIVING_ADDRESSES NSLocalizedString(@"Archiving addresses", nil)
#define BC_STRING_ARGUMENT_ADDRESS NSLocalizedString(@"%d address", nil)
#define BC_STRING_ARGUMENT_ADDRESSES NSLocalizedString(@"%d addresses", nil)
#define BC_STRING_AT_LEAST_ONE_ADDRESS_REQUIRED NSLocalizedString(@"You must have at least one active address", nil)
#define BC_STRING_BITCOIN_CASH_WARNING_CONFIRM_VALID_ADDRESS_ONE NSLocalizedString(@"Are you sure this is a bitcoin cash address?", nil)
#define BC_STRING_BITCOIN_CASH_WARNING_CONFIRM_VALID_ADDRESS_TWO NSLocalizedString(@"Sending funds to a bitcoin address by accident will result in loss of funds.", nil)
#define BC_STRING_BITPAY_INVOICE_EXPIRED_MESSAGE NSLocalizedString(@"An invoice is only valid for 15 minutes. Return to the merchant if you would like to resubmit a payment", nil)
#define BC_STRING_BITPAY_INVOICE_EXPIRED_TITLE NSLocalizedString(@"Bitpay Invoice Expired", nil)
#define BC_STRING_BITPAY_TIME_REMAINING NSLocalizedString(@"Time remaining %@", nil)
#define BC_STRING_CANCEL NSLocalizedString(@"Cancel", nil)
#define BC_STRING_CANCELLING NSLocalizedString(@"Cancelling", nil)
#define BC_STRING_CONFIRM_PAYMENT NSLocalizedString(@"Confirm Payment", nil)
#define BC_STRING_CONTINUE NSLocalizedString(@"Continue", nil)
#define BC_STRING_COPY_ADDRESS NSLocalizedString(@"Copy Address", nil)
#define BC_STRING_COPY_XPUB NSLocalizedString(@"Copy xPub", nil)
#define BC_STRING_CREATE NSLocalizedString(@"Create", nil)
#define BC_STRING_CUSTOM NSLocalizedString(@"Custom", nil)
#define BC_STRING_CUSTOM_FEE_WARNING NSLocalizedString(@"This feature is recommended for advanced users only. By choosing a custom fee, you risk overpaying or your transaction may get stuck.", nil)
#define BC_STRING_DECRYPTING_PRIVATE_KEY NSLocalizedString(@"Decrypting Private Key", nil)
#define BC_STRING_DEFAULT NSLocalizedString(@"Default", nil)
#define BC_STRING_DESCRIPTION NSLocalizedString(@"Description", nil)
#define BC_STRING_DONE NSLocalizedString(@"Done", nil)
#define BC_STRING_ENTER_BITCOIN_ADDRESS_OR_SELECT NSLocalizedString(@"Enter btc address or select", nil)
#define BC_STRING_ENTER_BITCOIN_CASH_ADDRESS_OR_SELECT NSLocalizedString(@"Enter bch address or select", nil)
#define BC_STRING_ENTER_ETHER_ADDRESS NSLocalizedString(@"Enter eth address", nil)
#define BC_STRING_ERROR NSLocalizedString(@"Error", nil)
#define BC_STRING_ERROR_GETTING_BALANCE_ARGUMENT_ASSET_ARGUMENT_MESSAGE NSLocalizedString(@"An error occurred when getting your %@ balance. Please try again later. Details: %@", nil)
#define BC_STRING_ERROR_SAVING_WALLET_CHECK_FOR_OTHER_DEVICES NSLocalizedString(@"An error occurred while saving your changes. Please make sure you are not logged into your wallet on another device.", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY NSLocalizedString(@"Extended Public Key", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY_DETAIL_HEADER_TITLE NSLocalizedString(@"Your xPub is an advanced feature that contains all of your public addresses.", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY_FOOTER_TITLE NSLocalizedString(@"Keep your xPub private. Someone with access to your xPub will be able to see all of your funds and transactions.", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY_WARNING NSLocalizedString(@"Sharing your xPub authorizes others to track your transaction history. As authorized persons may be able to disrupt you from accessing your wallet, only share your xPub with people you trust.", nil)
#define BC_STRING_FEE NSLocalizedString(@"Fee", nil)
#define BC_STRING_FEE_INFORMATION_DUST NSLocalizedString(@"This transaction requires a higher fee for dust consumption due to the small amount of change to be returned.", nil)
#define BC_STRING_FEE_INFORMATION_MESSAGE NSLocalizedString(@"Transaction fees impact how quickly the mining network will confirm your transactions, and depend on the current network conditions.", nil)
#define BC_STRING_FEE_INFORMATION_MESSAGE_APPEND_REGULAR_SEND NSLocalizedString(@" We recommend the fee shown for the transaction at this time.", nil)
#define BC_STRING_FEE_INFORMATION_TITLE NSLocalizedString(@"Transaction Fees", nil)
#define BC_STRING_FINISHED_SIGNING_INPUTS NSLocalizedString(@"Finished Signing Inputs", nil)
#define BC_STRING_FROM NSLocalizedString(@"From", nil)
#define BC_STRING_FROM_TO_ADDRESS_DIFFERENT NSLocalizedString(@"From and destination address have to be different", nil)
#define BC_STRING_FROM_TO_DIFFERENT NSLocalizedString(@"From and destination have to be different", nil)
#define BC_STRING_GREATER_THAN_ONE_HOUR NSLocalizedString(@"1+ hour", nil)
#define BC_STRING_HIGH_FEE_NOT_NECESSARY NSLocalizedString(@"High fee not necessary", nil)
#define BC_STRING_HIGH_FEE_WARNING_MESSAGE NSLocalizedString(@"This is an oversized bitcoin transaction. Your wallet needs to consolidate many smaller payments you've received in the past. This requires a relatively high fee in order to be confirmed quickly. If it’s fine for the transaction to take longer to confirm, you can reduce the fee manually by tapping \"Customize Fee.\"", nil)
#define BC_STRING_HIGH_FEE_WARNING_TITLE NSLocalizedString(@"Large Transaction", nil)
#define BC_STRING_IDENTIFIER NSLocalizedString(@"Identifier", nil)
#define BC_STRING_IMPORT_ADDRESS NSLocalizedString(@"Import address", nil)
#define BC_STRING_IMPORTED_ADDRESSES NSLocalizedString(@"Imported Addresses", nil)
#define BC_STRING_INVALID_EMAIL_ADDRESS NSLocalizedString(@"Invalid email address.", nil)
#define BC_STRING_INVALID_RECOVERY_PHRASE NSLocalizedString(@"Invalid recovery phrase. Please try again", nil)
#define BC_STRING_INVALID_SEND_VALUE NSLocalizedString(@"Invalid Send Value", nil)
#define BC_STRING_INVALID_TO_BITCOIN_ADDRESS NSLocalizedString(@"Invalid to bitcoin address", nil)
#define BC_STRING_LABEL NSLocalizedString(@"Label", nil)
#define BC_STRING_LABEL_ADDRESS NSLocalizedString(@"Label Address", nil)
#define BC_STRING_LABEL_MUST_BE_ALPHANUMERIC NSLocalizedString(@"Label must contain letters and numbers only", nil)
#define BC_STRING_LABEL_MUST_HAVE_LESS_THAN_18_CHAR NSLocalizedString(@"Label must have less than 18 characters", nil)
#define BC_STRING_LEARN_MORE NSLocalizedString(@"Learn More", nil)
#define BC_STRING_LESS_THAN_ONE_HOUR NSLocalizedString(@"~0–60 min", nil)
#define BC_STRING_LOADING_CREATING NSLocalizedString(@"Creating", nil)
#define BC_STRING_LOADING_CREATING_NEW_ADDRESS NSLocalizedString(@"Creating new address", nil)
#define BC_STRING_LOADING_CREATING_V3_WALLET NSLocalizedString(@"Creating V3 Wallet", nil)
#define BC_STRING_LOADING_LOADING_TRANSACTIONS NSLocalizedString(@"Loading transactions", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET NSLocalizedString(@"Recovering Funds", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET_ARGUMENT_FUNDS_ARGUMENT NSLocalizedString(@"Found %d, with %@", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET_CHECKING_ARGUMENT_OF_ARGUMENT NSLocalizedString(@"Checking for more: Step %d of %d", nil)
#define BC_STRING_LOW_FEE_NOT_RECOMMENDED NSLocalizedString(@"Low fee not recommended", nil)
#define BC_STRING_MAKE_DEFAULT NSLocalizedString(@"Make Default", nil)
#define BC_STRING_MUST_BE_ABOVE_OR_EQUAL_TO_DUST_THRESHOLD NSLocalizedString(@"Amount must be greater than or equal to the dust threshold (%lld Satoshi)", nil)
#define BC_STRING_MY_BITCOIN_WALLET NSLocalizedString(@"My Bitcoin Wallet", nil)
#define BC_STRING_NAME NSLocalizedString(@"Name", nil)
#define BC_STRING_NEW_ADDRESS NSLocalizedString(@"New Address", nil)
#define BC_STRING_NEW_ADDRESS_CREATE_NEW NSLocalizedString(@"Create new address", nil)
#define BC_STRING_NO_ADDRESSES_WITH_SPENDABLE_BALANCE_ABOVE_OR_EQUAL_TO_DUST NSLocalizedString(@"You have no addresses with a spendable balance greater than or equal to the required dust threshold.", nil)
#define BC_STRING_NO_AVAILABLE_FUNDS NSLocalizedString(@"You have no available funds to send from this address", nil)
#define BC_STRING_NO_DESCRIPTION NSLocalizedString(@"No description", nil)
#define BC_STRING_NO_LABEL NSLocalizedString(@"No Label", nil)
#define BC_STRING_NOT_ENOUGH_FUNDS_TO_USE_FEE NSLocalizedString(@"You do not have enough funds to use this fee.", nil)
#define BC_STRING_NOT_NOW NSLocalizedString(@"Not now", nil)
#define BC_STRING_OK NSLocalizedString(@"OK", nil)
#define BC_STRING_PAYMENT_ASK_TO_ARCHIVE_TRANSFERRED_ADDRESSES NSLocalizedString(@"Would you like to archive the addresses used?", nil)
#define BC_STRING_PAYMENT_SENT NSLocalizedString(@"Payment Sent!", nil)
#define BC_STRING_PAYMENT_TRANSFERRED_FROM_ARGUMENT_ARGUMENT NSLocalizedString(@"Transferred funds from %d %@", nil)
#define BC_STRING_PAYMENT_TRANSFERRED_FROM_ARGUMENT_ARGUMENT_OUTPUTS_ARGUMENT_ARGUMENT_TOO_SMALL NSLocalizedString(@"Transferred funds from %d %@. Outputs for %d %@ were too small.", nil)
#define BC_STRING_PAYMENTS_SENT NSLocalizedString(@"Payments Sent", nil)
#define BC_STRING_PLEASE_SELECT_DIFFERENT_ADDRESS NSLocalizedString(@"Please select a different address to send from.", nil)
#define BC_STRING_PRIORITY NSLocalizedString(@"Priority", nil)
#define BC_STRING_REGULAR NSLocalizedString(@"Regular", nil)
#define BC_STRING_SATOSHI_PER_BYTE_ABBREVIATED NSLocalizedString(@"sat/b", nil)
#define BC_STRING_SAVE NSLocalizedString(@"Save", nil)
#define BC_STRING_SCAN_PRIVATE_KEY NSLocalizedString(@"Scan Private Key", nil)
#define BC_STRING_SEND NSLocalizedString(@"Send", nil)
#define BC_STRING_SEND_ERROR_FEE_TOO_LOW NSLocalizedString(@"The fee you have specified is too low.", nil)
#define BC_STRING_SEND_ERROR_NO_INTERNET_CONNECTION NSLocalizedString(@"No internet connection available. Please check your network settings.", nil)
#define BC_STRING_SEND_FROM NSLocalizedString(@"Send from...", nil)
#define BC_STRING_SEND_TO NSLocalizedString(@"Send to...", nil)
#define BC_STRING_SENDING_TRANSACTION NSLocalizedString(@"Sending Transaction", nil)
#define BC_STRING_SET_DEFAULT_ACCOUNT NSLocalizedString(@"Set as Default?", nil)
#define BC_STRING_SETTINGS_ERROR_LOADING_MESSAGE NSLocalizedString(@"Please check your internet connection.", nil)
#define BC_STRING_SETTINGS_ERROR_LOADING_TITLE NSLocalizedString(@"Error loading settings", nil)
#define BC_STRING_SETTINGS_ERROR_UPDATING_TITLE NSLocalizedString(@"Error updating settings", nil)
#define BC_STRING_SIGNING_INPUT NSLocalizedString(@"Signing Input %d", nil)
#define BC_STRING_SIGNING_INPUTS NSLocalizedString(@"Signing Inputs", nil)
#define BC_STRING_SOME_FUNDS_CANNOT_BE_TRANSFERRED_AUTOMATICALLY NSLocalizedString(@"Some funds cannot be transferred automatically.", nil)
#define BC_STRING_SOMETHING_WENT_WRONG_CHECK_INTERNET_CONNECTION NSLocalizedString(@"An error occurred while updating your spendable balance. Please check your internet connection and try again.", nil)
#define BC_STRING_SURGE_OCCURRING_MESSAGE NSLocalizedString(@"The Bitcoin mining network is currently experiencing a high volume of activity, resulting in recommended fees that are higher than usual.", nil)
#define BC_STRING_TO NSLocalizedString(@"To", nil)
#define BC_STRING_TOTAL NSLocalizedString(@"Total", nil)
#define BC_STRING_TOTAL_BALANCE NSLocalizedString(@"Total Balance", nil)
#define BC_STRING_TRANSACTION_DESCRIPTION_PLACEHOLDER NSLocalizedString(@"What's this for?", nil)
#define BC_STRING_TRANSFER_ALL_CALCULATING_AMOUNTS_AND_FEES_ARGUMENT_OF_ARGUMENT NSLocalizedString(@"Calculating: Address %@ of %@", nil)
#define BC_STRING_TRANSFER_ALL_FROM_ADDRESS_ARGUMENT_ARGUMENT NSLocalizedString(@"Transferring all funds: Address %i of %i", nil)
#define BC_STRING_TRANSFER_ALL_PREPARING_TRANSFER NSLocalizedString(@"Preparing transfer", nil)
#define BC_STRING_TRANSFER_AMOUNT NSLocalizedString(@"Transfer Amount", nil)
#define BC_STRING_TRANSFER_FOOTER_TITLE NSLocalizedString(@"For your safety, we recommend you to transfer any balances in your imported addresses into your Blockchain wallet.", nil)
#define BC_STRING_TRANSFER_FUNDS NSLocalizedString(@"Transfer Funds", nil)
#define BC_STRING_TRANSFER_FUNDS_DESCRIPTION_ONE NSLocalizedString(@"For your safety, we recommend you to transfer any balances in your imported addresses into your Blockchain wallet.", nil)
#define BC_STRING_TRANSFER_FUNDS_DESCRIPTION_TWO NSLocalizedString(@"Your transferred funds will be safe and secure, and you'll benefit from increased privacy and convenient backup and recovery features.", nil)
#define BC_STRING_UNARCHIVE NSLocalizedString(@"Unarchive", nil)
#define BC_STRING_USE_TOTAL_AVAILABLE_MINUS_FEE_ARGUMENT NSLocalizedString(@"Use total available minus fee: %@", nil)
#define BC_STRING_WALLETS NSLocalizedString(@"Wallets", nil)
#define BC_STRING_WARNING_TITLE NSLocalizedString(@"Warning", nil)
#define BC_STRING_WATCH_ONLY NSLocalizedString(@"Watch Only", nil)
#define BC_STRING_WATCH_ONLY_FOOTER_TITLE NSLocalizedString(@"This is a watch-only address. To spend your funds from this wallet, please scan your private key.", nil)
#define BC_STRING_YOU_MUST_ENTER_A_LABEL NSLocalizedString(@"You must enter a label", nil)
#define BC_STRING_YOU_MUST_ENTER_DESTINATION_ADDRESS NSLocalizedString(@"You must enter a destination address", nil)
