// Copyright © Blockchain Luxembourg S.A. All rights reserved.

#import <Foundation/Foundation.h>

#define BC_STRING_ADDRESS NSLocalizedString(@"Address", nil)
#define BC_STRING_ADDRESSES NSLocalizedString(@"Addresses", nil)
#define BC_STRING_ARCHIVE NSLocalizedString(@"Archive", nil)
#define BC_STRING_ARCHIVE_FOOTER_TITLE NSLocalizedString(@"Archive this if you do NOT want to use it anymore. Your funds will remain safe, and you can unarchive it at any time.", nil)
#define BC_STRING_ARCHIVED NSLocalizedString(@"Archived", nil)
#define BC_STRING_ARCHIVED_FOOTER_TITLE NSLocalizedString(@"This is archived. Though you cannot send funds from here, any and all funds will remain safe. Simply unarchive to start using it again.", nil)
#define BC_STRING_ARCHIVING_ADDRESSES NSLocalizedString(@"Archiving addresses", nil)
#define BC_STRING_AT_LEAST_ONE_ADDRESS_REQUIRED NSLocalizedString(@"You must have at least one active address", nil)
#define BC_STRING_CANCEL NSLocalizedString(@"Cancel", nil)
#define BC_STRING_CONTINUE NSLocalizedString(@"Continue", nil)
#define BC_STRING_COPY_ADDRESS NSLocalizedString(@"Copy Address", nil)
#define BC_STRING_COPY_XPUB NSLocalizedString(@"Copy xPub", nil)
#define BC_STRING_CREATE NSLocalizedString(@"Create", nil)
#define BC_STRING_DECRYPTING_PRIVATE_KEY NSLocalizedString(@"Decrypting Private Key", nil)
#define BC_STRING_DEFAULT NSLocalizedString(@"Default", nil)
#define BC_STRING_DONE NSLocalizedString(@"Done", nil)
#define BC_STRING_ERROR NSLocalizedString(@"Error", nil)
#define BC_STRING_ERROR_SAVING_WALLET_CHECK_FOR_OTHER_DEVICES NSLocalizedString(@"An error occurred while saving your changes. Please make sure you are not logged into your wallet on another device.", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY NSLocalizedString(@"Extended Public Key", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY_DETAIL_HEADER_TITLE NSLocalizedString(@"Your xPub is an advanced feature that contains all of your public addresses.", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY_FOOTER_TITLE NSLocalizedString(@"Keep your xPub private. Someone with access to your xPub will be able to see all of your funds and transactions.", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY_WARNING NSLocalizedString(@"Sharing your xPub authorizes others to track your transaction history. As authorized persons may be able to disrupt you from accessing your wallet, only share your xPub with people you trust.", nil)
#define BC_STRING_IDENTIFIER NSLocalizedString(@"Identifier", nil)
#define BC_STRING_IMPORT_ADDRESS NSLocalizedString(@"Import address", nil)
#define BC_STRING_IMPORTED_ADDRESSES NSLocalizedString(@"Imported Addresses", nil)
#define BC_STRING_INVALID_EMAIL_ADDRESS NSLocalizedString(@"Invalid email address.", nil)
#define BC_STRING_INVALID_RECOVERY_PHRASE NSLocalizedString(@"Invalid recovery phrase. Please try again", nil)
#define BC_STRING_LABEL NSLocalizedString(@"Label", nil)
#define BC_STRING_LABEL_ADDRESS NSLocalizedString(@"Label Address", nil)
#define BC_STRING_LABEL_MUST_BE_ALPHANUMERIC NSLocalizedString(@"Label must contain letters and numbers only", nil)
#define BC_STRING_LABEL_MUST_HAVE_LESS_THAN_18_CHAR NSLocalizedString(@"Label must have less than 18 characters", nil)
#define BC_STRING_LEARN_MORE NSLocalizedString(@"Learn More", nil)
#define BC_STRING_LOADING_CREATING NSLocalizedString(@"Creating", nil)
#define BC_STRING_LOADING_CREATING_NEW_ADDRESS NSLocalizedString(@"Creating new address", nil)
#define BC_STRING_LOADING_LOADING_TRANSACTIONS NSLocalizedString(@"Loading transactions", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET NSLocalizedString(@"Recovering Funds", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET_ARGUMENT_FUNDS_ARGUMENT NSLocalizedString(@"Found %d, with %@", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET_CHECKING_ARGUMENT_OF_ARGUMENT NSLocalizedString(@"Checking for more: Step %d of %d", nil)
#define BC_STRING_MAKE_DEFAULT NSLocalizedString(@"Make Default", nil)
#define BC_STRING_NAME NSLocalizedString(@"Name", nil)
#define BC_STRING_NEW_ADDRESS NSLocalizedString(@"New Address", nil)
#define BC_STRING_NEW_ADDRESS_CREATE_NEW NSLocalizedString(@"Create new address", nil)
#define BC_STRING_NO_LABEL NSLocalizedString(@"No Label", nil)
#define BC_STRING_NOT_NOW NSLocalizedString(@"Not now", nil)
#define BC_STRING_OK NSLocalizedString(@"OK", nil)
#define BC_STRING_SAVE NSLocalizedString(@"Save", nil)
#define BC_STRING_SCAN_PRIVATE_KEY NSLocalizedString(@"Scan Private Key", nil)
#define BC_STRING_SET_DEFAULT_ACCOUNT NSLocalizedString(@"Set as Default?", nil)
#define BC_STRING_SETTINGS_ERROR_LOADING_MESSAGE NSLocalizedString(@"Please check your internet connection.", nil)
#define BC_STRING_SETTINGS_ERROR_LOADING_TITLE NSLocalizedString(@"Error loading settings", nil)
#define BC_STRING_SETTINGS_ERROR_UPDATING_TITLE NSLocalizedString(@"Error updating settings", nil)
#define BC_STRING_TRANSACTION_DESCRIPTION_PLACEHOLDER NSLocalizedString(@"What's this for?", nil)
#define BC_STRING_TRANSFER_FUNDS NSLocalizedString(@"Transfer Funds", nil)
#define BC_STRING_TRANSFER_FUNDS_DESCRIPTION_ONE NSLocalizedString(@"For your safety, we recommend you to transfer any balances in your imported addresses into your Blockchain wallet.", nil)
#define BC_STRING_TRANSFER_FUNDS_DESCRIPTION_TWO NSLocalizedString(@"Your transferred funds will be safe and secure, and you'll benefit from increased privacy and convenient backup and recovery features.", nil)
#define BC_STRING_UNARCHIVE NSLocalizedString(@"Unarchive", nil)
#define BC_STRING_WALLETS NSLocalizedString(@"Wallets", nil)
#define BC_STRING_WARNING_TITLE NSLocalizedString(@"Warning", nil)
#define BC_STRING_WATCH_ONLY NSLocalizedString(@"Watch Only", nil)
#define BC_STRING_WATCH_ONLY_FOOTER_TITLE NSLocalizedString(@"This is a watch-only address. To spend your funds from this wallet, please scan your private key.", nil)
#define BC_STRING_YOU_MUST_ENTER_A_LABEL NSLocalizedString(@"You must enter a label", nil)
