//
//  LocalizationConstants+ObjCStrings.swift
//  Localization
//
//  Created by Paulo on 08/01/2021.
//  Copyright © 2021 Blockchain Luxembourg S.A. All rights reserved.
//

// swiftlint:disable all

import Foundation

extension LocalizationConstants {
    /// Redefine strings from `Blockchain/LocalizationConstants.h` so they can be captured by any tool used for requesting translations.
    /// This should not be used by non-objc code.
    public enum ObjCStrings { }
}

extension LocalizationConstants.ObjCStrings {
    public static let BC_STRING_ADDRESS = NSLocalizedString("Address", comment: "")
    public static let BC_STRING_ADDRESS_BOOK = NSLocalizedString("Address book", comment: "")
    public static let BC_STRING_ADDRESSES = NSLocalizedString("Addresses", comment: "")
    public static let BC_STRING_ADVANCED_USERS_ONLY = NSLocalizedString("Advanced users only", comment: "")
    public static let BC_STRING_AMOUNT = NSLocalizedString("Amount", comment: "")
    public static let BC_STRING_ANY_ADDRESS = NSLocalizedString("Any address", comment: "")
    public static let BC_STRING_ARCHIVE = NSLocalizedString("Archive", comment: "")
    public static let BC_STRING_ARCHIVE_FOOTER_TITLE = NSLocalizedString("Archive this if you do NOT want to use it anymore. Your funds will remain safe, and you can unarchive it at any time.", comment: "")
    public static let BC_STRING_ARCHIVED = NSLocalizedString("Archived", comment: "")
    public static let BC_STRING_ARCHIVED_FOOTER_TITLE = NSLocalizedString("This is archived. Though you cannot send funds from here, any and all funds will remain safe. Simply unarchive to start using it again.", comment: "")
    public static let BC_STRING_ARCHIVING_ADDRESSES = NSLocalizedString("Archiving addresses", comment: "")
    public static let BC_STRING_ARGUMENT_ADDRESS = NSLocalizedString("%d address", comment: "")
    public static let BC_STRING_ARGUMENT_ADDRESSES = NSLocalizedString("%d addresses", comment: "")
    public static let BC_STRING_AT_LEAST_ONE_ADDRESS_REQUIRED = NSLocalizedString("You must have at least one active address", comment: "")
    public static let BC_STRING_BITCOIN_CASH_WARNING_CONFIRM_VALID_ADDRESS_ONE = NSLocalizedString("Are you sure this is a bitcoin cash address?", comment: "")
    public static let BC_STRING_BITCOIN_CASH_WARNING_CONFIRM_VALID_ADDRESS_TWO = NSLocalizedString("Sending funds to a bitcoin address by accident will result in loss of funds.", comment: "")
    public static let BC_STRING_BITPAY_INVOICE_EXPIRED_MESSAGE = NSLocalizedString("An invoice is only valid for 15 minutes. Return to the merchant if you would like to resubmit a payment", comment: "")
    public static let BC_STRING_BITPAY_INVOICE_EXPIRED_TITLE = NSLocalizedString("Bitpay Invoice Expired", comment: "")
    public static let BC_STRING_BITPAY_TIME_REMAINING = NSLocalizedString("Time remaining %@", comment: "")
    public static let BC_STRING_CANCEL = NSLocalizedString("Cancel", comment: "")
    public static let BC_STRING_CANCELLING = NSLocalizedString("Cancelling", comment: "")
    public static let BC_STRING_CONFIRM_PAYMENT = NSLocalizedString("Confirm Payment", comment: "")
    public static let BC_STRING_CONTINUE = NSLocalizedString("Continue", comment: "")
    public static let BC_STRING_COPY_ADDRESS = NSLocalizedString("Copy Address", comment: "")
    public static let BC_STRING_COPY_XPUB = NSLocalizedString("Copy xPub", comment: "")
    public static let BC_STRING_CREATE = NSLocalizedString("Create", comment: "")
    public static let BC_STRING_CUSTOM = NSLocalizedString("Custom", comment: "")
    public static let BC_STRING_CUSTOM_FEE_WARNING = NSLocalizedString("This feature is recommended for advanced users only. By choosing a custom fee, you risk overpaying or your transaction may get stuck.", comment: "")
    public static let BC_STRING_DECRYPTING_PRIVATE_KEY = NSLocalizedString("Decrypting Private Key", comment: "")
    public static let BC_STRING_DEFAULT = NSLocalizedString("Default", comment: "")
    public static let BC_STRING_DESCRIPTION = NSLocalizedString("Description", comment: "")
    public static let BC_STRING_DONE = NSLocalizedString("Done", comment: "")
    public static let BC_STRING_ENTER_BITCOIN_ADDRESS_OR_SELECT = NSLocalizedString("Enter btc address or select", comment: "")
    public static let BC_STRING_ENTER_BITCOIN_CASH_ADDRESS_OR_SELECT = NSLocalizedString("Enter bch address or select", comment: "")
    public static let BC_STRING_ENTER_ETHER_ADDRESS = NSLocalizedString("Enter eth address", comment: "")
    public static let BC_STRING_ERROR = NSLocalizedString("Error", comment: "")
    public static let BC_STRING_ERROR_GETTING_BALANCE_ARGUMENT_ASSET_ARGUMENT_MESSAGE = NSLocalizedString("An error occurred when getting your %@ balance. Please try again later. Details: %@", comment: "")
    public static let BC_STRING_ERROR_SAVING_WALLET_CHECK_FOR_OTHER_DEVICES = NSLocalizedString("An error occurred while saving your changes. Please make sure you are not logged into your wallet on another device.", comment: "")
    public static let BC_STRING_EXTENDED_PUBLIC_KEY = NSLocalizedString("Extended Public Key", comment: "")
    public static let BC_STRING_EXTENDED_PUBLIC_KEY_DETAIL_HEADER_TITLE = NSLocalizedString("Your xPub is an advanced feature that contains all of your public addresses.", comment: "")
    public static let BC_STRING_EXTENDED_PUBLIC_KEY_FOOTER_TITLE = NSLocalizedString("Keep your xPub private. Someone with access to your xPub will be able to see all of your funds and transactions.", comment: "")
    public static let BC_STRING_EXTENDED_PUBLIC_KEY_WARNING = NSLocalizedString("Sharing your xPub authorizes others to track your transaction history. As authorized persons may be able to disrupt you from accessing your wallet, only share your xPub with people you trust.", comment: "")
    public static let BC_STRING_FEE = NSLocalizedString("Fee", comment: "")
    public static let BC_STRING_FEE_INFORMATION_DUST = NSLocalizedString("This transaction requires a higher fee for dust consumption due to the small amount of change to be returned.", comment: "")
    public static let BC_STRING_FEE_INFORMATION_MESSAGE = NSLocalizedString("Transaction fees impact how quickly the mining network will confirm your transactions, and depend on the current network conditions.", comment: "")
    public static let BC_STRING_FEE_INFORMATION_MESSAGE_APPEND_REGULAR_SEND = NSLocalizedString(" We recommend the fee shown for the transaction at this time.", comment: "")
    public static let BC_STRING_FEE_INFORMATION_TITLE = NSLocalizedString("Transaction Fees", comment: "")
    public static let BC_STRING_FINISHED_SIGNING_INPUTS = NSLocalizedString("Finished Signing Inputs", comment: "")
    public static let BC_STRING_FROM = NSLocalizedString("From", comment: "")
    public static let BC_STRING_FROM_TO_ADDRESS_DIFFERENT = NSLocalizedString("From and destination address have to be different", comment: "")
    public static let BC_STRING_FROM_TO_DIFFERENT = NSLocalizedString("From and destination have to be different", comment: "")
    public static let BC_STRING_GREATER_THAN_ONE_HOUR = NSLocalizedString("1+ hour", comment: "")
    public static let BC_STRING_HIGH_FEE_NOT_NECESSARY = NSLocalizedString("High fee not necessary", comment: "")
    public static let BC_STRING_HIGH_FEE_WARNING_MESSAGE = NSLocalizedString("This is an oversized bitcoin transaction. Your wallet needs to consolidate many smaller payments you've received in the past. This requires a relatively high fee in order to be confirmed quickly. If it’s fine for the transaction to take longer to confirm, you can reduce the fee manually by tapping \"Customize Fee.\"", comment: "")
    public static let BC_STRING_HIGH_FEE_WARNING_TITLE = NSLocalizedString("Large Transaction", comment: "")
    public static let BC_STRING_IDENTIFIER = NSLocalizedString("Identifier", comment: "")
    public static let BC_STRING_IMPORT_ADDRESS = NSLocalizedString("Import address", comment: "")
    public static let BC_STRING_IMPORTED_ADDRESSES = NSLocalizedString("Imported Addresses", comment: "")
    public static let BC_STRING_INVALID_EMAIL_ADDRESS = NSLocalizedString("Invalid email address.", comment: "")
    public static let BC_STRING_INVALID_RECOVERY_PHRASE = NSLocalizedString("Invalid recovery phrase. Please try again", comment: "")
    public static let BC_STRING_INVALID_SEND_VALUE = NSLocalizedString("Invalid Send Value", comment: "")
    public static let BC_STRING_INVALID_TO_BITCOIN_ADDRESS = NSLocalizedString("Invalid to bitcoin address", comment: "")
    public static let BC_STRING_LABEL = NSLocalizedString("Label", comment: "")
    public static let BC_STRING_LABEL_ADDRESS = NSLocalizedString("Label Address", comment: "")
    public static let BC_STRING_LABEL_MUST_BE_ALPHANUMERIC = NSLocalizedString("Label must contain letters and numbers only", comment: "")
    public static let BC_STRING_LABEL_MUST_HAVE_LESS_THAN_18_CHAR = NSLocalizedString("Label must have less than 18 characters", comment: "")
    public static let BC_STRING_LEARN_MORE = NSLocalizedString("Learn More", comment: "")
    public static let BC_STRING_LESS_THAN_ONE_HOUR = NSLocalizedString("~0–60 min", comment: "")
    public static let BC_STRING_LOADING_CREATING = NSLocalizedString("Creating", comment: "")
    public static let BC_STRING_LOADING_CREATING_NEW_ADDRESS = NSLocalizedString("Creating new address", comment: "")
    public static let BC_STRING_LOADING_CREATING_V3_WALLET = NSLocalizedString("Creating V3 Wallet", comment: "")
    public static let BC_STRING_LOADING_LOADING_TRANSACTIONS = NSLocalizedString("Loading transactions", comment: "")
    public static let BC_STRING_LOADING_RECOVERING_WALLET = NSLocalizedString("Recovering Funds", comment: "")
    public static let BC_STRING_LOADING_RECOVERING_WALLET_ARGUMENT_FUNDS_ARGUMENT = NSLocalizedString("Found %d, with %@", comment: "")
    public static let BC_STRING_LOADING_RECOVERING_WALLET_CHECKING_ARGUMENT_OF_ARGUMENT = NSLocalizedString("Checking for more: Step %d of %d", comment: "")
    public static let BC_STRING_LOW_FEE_NOT_RECOMMENDED = NSLocalizedString("Low fee not recommended", comment: "")
    public static let BC_STRING_MAKE_DEFAULT = NSLocalizedString("Make Default", comment: "")
    public static let BC_STRING_MUST_BE_ABOVE_OR_EQUAL_TO_DUST_THRESHOLD = NSLocalizedString("Amount must be greater than or equal to the dust threshold (%lld Satoshi)", comment: "")
    public static let BC_STRING_NAME = NSLocalizedString("Name", comment: "")
    public static let BC_STRING_NEW_ADDRESS = NSLocalizedString("New Address", comment: "")
    public static let BC_STRING_NEW_ADDRESS_CREATE_NEW = NSLocalizedString("Create new address", comment: "")
    public static let BC_STRING_NO_ADDRESSES_WITH_SPENDABLE_BALANCE_ABOVE_OR_EQUAL_TO_DUST = NSLocalizedString("You have no addresses with a spendable balance greater than or equal to the required dust threshold.", comment: "")
    public static let BC_STRING_NO_AVAILABLE_FUNDS = NSLocalizedString("You have no available funds to send from this address", comment: "")
    public static let BC_STRING_NO_DESCRIPTION = NSLocalizedString("No description", comment: "")
    public static let BC_STRING_NO_LABEL = NSLocalizedString("No Label", comment: "")
    public static let BC_STRING_NOT_ENOUGH_FUNDS_TO_USE_FEE = NSLocalizedString("You do not have enough funds to use this fee.", comment: "")
    public static let BC_STRING_NOT_NOW = NSLocalizedString("Not now", comment: "")
    public static let BC_STRING_OK = NSLocalizedString("OK", comment: "")
    public static let BC_STRING_PAYMENT_ASK_TO_ARCHIVE_TRANSFERRED_ADDRESSES = NSLocalizedString("Would you like to archive the addresses used?", comment: "")
    public static let BC_STRING_PAYMENT_SENT = NSLocalizedString("Payment Sent!", comment: "")
    public static let BC_STRING_PAYMENT_TRANSFERRED_FROM_ARGUMENT_ARGUMENT = NSLocalizedString("Transferred funds from %d %@", comment: "")
    public static let BC_STRING_PAYMENT_TRANSFERRED_FROM_ARGUMENT_ARGUMENT_OUTPUTS_ARGUMENT_ARGUMENT_TOO_SMALL = NSLocalizedString("Transferred funds from %d %@. Outputs for %d %@ were too small.", comment: "")
    public static let BC_STRING_PAYMENTS_SENT = NSLocalizedString("Payments Sent", comment: "")
    public static let BC_STRING_PLEASE_SELECT_DIFFERENT_ADDRESS = NSLocalizedString("Please select a different address to send from.", comment: "")
    public static let BC_STRING_PRIORITY = NSLocalizedString("Priority", comment: "")
    public static let BC_STRING_REGULAR = NSLocalizedString("Regular", comment: "")
    public static let BC_STRING_SATOSHI_PER_BYTE_ABBREVIATED = NSLocalizedString("sat/b", comment: "")
    public static let BC_STRING_SAVE = NSLocalizedString("Save", comment: "")
    public static let BC_STRING_SCAN_PRIVATE_KEY = NSLocalizedString("Scan Private Key", comment: "")
    public static let BC_STRING_SEND = NSLocalizedString("Send", comment: "")
    public static let BC_STRING_SEND_ERROR_FEE_TOO_LOW = NSLocalizedString("The fee you have specified is too low.", comment: "")
    public static let BC_STRING_SEND_ERROR_NO_INTERNET_CONNECTION = NSLocalizedString("No internet connection available. Please check your network settings.", comment: "")
    public static let BC_STRING_SEND_FROM = NSLocalizedString("Send from...", comment: "")
    public static let BC_STRING_SEND_TO = NSLocalizedString("Send to...", comment: "")
    public static let BC_STRING_SENDING_TRANSACTION = NSLocalizedString("Sending Transaction", comment: "")
    public static let BC_STRING_SET_DEFAULT_ACCOUNT = NSLocalizedString("Set as Default?", comment: "")
    public static let BC_STRING_SETTINGS_ERROR_LOADING_MESSAGE = NSLocalizedString("Please check your internet connection.", comment: "")
    public static let BC_STRING_SETTINGS_ERROR_LOADING_TITLE = NSLocalizedString("Error loading settings", comment: "")
    public static let BC_STRING_SETTINGS_ERROR_UPDATING_TITLE = NSLocalizedString("Error updating settings", comment: "")
    public static let BC_STRING_SIGNING_INPUT = NSLocalizedString("Signing Input %d", comment: "")
    public static let BC_STRING_SIGNING_INPUTS = NSLocalizedString("Signing Inputs", comment: "")
    public static let BC_STRING_SOME_FUNDS_CANNOT_BE_TRANSFERRED_AUTOMATICALLY = NSLocalizedString("Some funds cannot be transferred automatically.", comment: "")
    public static let BC_STRING_SOMETHING_WENT_WRONG_CHECK_INTERNET_CONNECTION = NSLocalizedString("An error occurred while updating your spendable balance. Please check your internet connection and try again.", comment: "")
    public static let BC_STRING_SURGE_OCCURRING_MESSAGE = NSLocalizedString("The Bitcoin mining network is currently experiencing a high volume of activity, resulting in recommended fees that are higher than usual.", comment: "")
    public static let BC_STRING_TO = NSLocalizedString("To", comment: "")
    public static let BC_STRING_TOTAL = NSLocalizedString("Total", comment: "")
    public static let BC_STRING_TOTAL_BALANCE = NSLocalizedString("Total Balance", comment: "")
    public static let BC_STRING_TRANSACTION_DESCRIPTION_PLACEHOLDER = NSLocalizedString("What's this for?", comment: "")
    public static let BC_STRING_TRANSFER_ALL_CALCULATING_AMOUNTS_AND_FEES_ARGUMENT_OF_ARGUMENT = NSLocalizedString("Calculating: Address %@ of %@", comment: "")
    public static let BC_STRING_TRANSFER_ALL_FROM_ADDRESS_ARGUMENT_ARGUMENT = NSLocalizedString("Transferring all funds: Address %i of %i", comment: "")
    public static let BC_STRING_TRANSFER_ALL_PREPARING_TRANSFER = NSLocalizedString("Preparing transfer", comment: "")
    public static let BC_STRING_TRANSFER_AMOUNT = NSLocalizedString("Transfer Amount", comment: "")
    public static let BC_STRING_TRANSFER_FOOTER_TITLE = NSLocalizedString("For your safety, we recommend you to transfer any balances in your imported addresses into your Blockchain wallet.", comment: "")
    public static let BC_STRING_TRANSFER_FUNDS = NSLocalizedString("Transfer Funds", comment: "")
    public static let BC_STRING_TRANSFER_FUNDS_DESCRIPTION_ONE = NSLocalizedString("For your safety, we recommend you to transfer any balances in your imported addresses into your Blockchain wallet.", comment: "")
    public static let BC_STRING_TRANSFER_FUNDS_DESCRIPTION_TWO = NSLocalizedString("Your transferred funds will be safe and secure, and you'll benefit from increased privacy and convenient backup and recovery features.", comment: "")
    public static let BC_STRING_UNARCHIVE = NSLocalizedString("Unarchive", comment: "")
    public static let BC_STRING_USE_TOTAL_AVAILABLE_MINUS_FEE_ARGUMENT = NSLocalizedString("Use total available minus fee: %@", comment: "")
    public static let BC_STRING_WALLETS = NSLocalizedString("Wallets", comment: "")
    public static let BC_STRING_WARNING_TITLE = NSLocalizedString("Warning", comment: "")
    public static let BC_STRING_WATCH_ONLY = NSLocalizedString("Watch Only", comment: "")
    public static let BC_STRING_WATCH_ONLY_FOOTER_TITLE = NSLocalizedString("This is a watch-only address. To spend your funds from this wallet, please scan your private key.", comment: "")
    public static let BC_STRING_YOU_MUST_ENTER_A_LABEL = NSLocalizedString("You must enter a label", comment: "")
    public static let BC_STRING_YOU_MUST_ENTER_DESTINATION_ADDRESS = NSLocalizedString("You must enter a destination address", comment: "")
}
